// TODO OBJETO É CRIADO A PARTIR DE UMA CLASSE
// A CLASSE É UM MOLDE QUE É UTILIZADO PARA CRIAR UM OBJETO
    // DENTRO DA CLASSE NOS CONSEGUIMOS DEFINIR ATRIBUTOS E METODOS QUE UM OBJETO RECEBERA.

// CRIANDO UMA CLASSE:

    class space {}

// PODEMOS CRIAR UM OBJETO ATRAVES DESSA CLASSE:

    let mySpace = new Space()
// AQUI ESTAMOS FAZENDO COM QUE O MYSPACE RECEBA UMA NOVA INSTANCIA DA NOSSA CLASSE SPACE